nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/':
      allow_origin: ['^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$']
