# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Voters
    App\Security\Voter\UserVoter:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'
        tags: ['security.voter']

    App\Security\Voter\CompanyVoter:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'
        tags: ['security.voter']

    App\Security\Voter\ProjectVoter:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['security.voter']

    # Providers
    App\DataProvider\UserDataProvider:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['api_platform.state_provider']
    
    App\State\CompanyCollectionProvider:
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['api_platform.state_provider']

    App\State\ProjectCollectionProvider:
        tags: ['api_platform.state_provider']

    App\State\ProjectItemProvider:
        tags: ['api_platform.state_provider']

    # Processors


    # Base Path
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\State\UserPasswordHasher:
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
            
    App\State\ProjectStateProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $security: '@Symfony\Bundle\SecurityBundle\Security'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['api_platform.state_processor']

    App\State\UserStateProcessor:
        arguments:
            $passwordHasher: '@App\State\UserPasswordHasher'
            $security: '@Symfony\Bundle\SecurityBundle\Security'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['api_platform.state_processor']
        
    
